package dao;

import dao.mappers.BookMapper;
import dao.uow.IUnitOfWork;
import domain.model.Book;
import domain.model.Person;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

public class BookRepository extends RepositoryBase<Book>
	implements IBookRepository {
	
	public BookRepository(Connection connection,
                          BookMapper mapper,
                          IRepository<Person> personRepo, IUnitOfWork uow) {
		super(connection, mapper,uow);
		mapper.setPersonRepo(personRepo);	
	}
	
	@Override
	protected String tableName() {
		// TODO Auto-generated method stub
		return "book";
	}
	@Override
	protected String createTableSql() {
		// TODO Auto-generated method stub
		return "CREATE TABLE book("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "person_id INT,"
				+ "amount DECIMAL," 
				+ "title VARCHAR(20),"
				+ ")";
	}
	@Override
	protected String insertSql() {
		// TODO Auto-generated method stub
		return "INSERT INTO book(person_id, amount, title) VALUES (?, ?, ?)";
	}
	@Override
	protected String deleteSql() {
		// TODO Auto-generated method stub
		return "DELETE FROM book WHERE ID = ?";
	}
	@Override
	protected String updateSql() {
		// TODO Auto-generated method stub
		return "UPDATE book SET person_id = ?, amount = ?, title = ? WHERE ID = ?";
	}
	@Override
	protected String selectByIdSql() {
		// TODO Auto-generated method stub
		return "SELECT * FROM book WHERE id=?";
	}
	@Override
	protected String selectAllSql() {
		// TODO Auto-generated method stub
		return "SELECT * FROM book";
	}
	
	@Override
	protected void setupInsert(Book entity) throws SQLException {
		insert.setInt(1, entity.getPersonId());
		insert.setDouble(2, entity.getAmount());
		insert.setString(3, entity.getTitle());
		
	}

	@Override
	protected void setupUpdate(Book entity) throws SQLException {
		update.setInt(1, entity.getPersonId());
		update.setDouble(2, entity.getAmount());
		update.setString(3, entity.getTitle());

}

	public List<Book> byPerson(Person person) {
		// TODO Auto-generated method stub
		return null;
	}
}
