package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import domain.model.Person;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

public class PersonRepository 
	extends RepositoryBase<Person> 
	implements IPersonRepository{
	
	public PersonRepository(Connection connection, 
			IMapResultSetIntoEntity<Person> mapper,
			IUnitOfWork uow) {
		super(connection, mapper,uow);
	}

	@Override
	protected String tableName() {
		return "person";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE person("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "surname VARCHAR(50)"
				+ ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO person(name,surname) VALUES(?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE PERSON set name=?, surname=? WHERE id=?";
	}


	@Override
	protected void setupInsert(Person entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
		
	}

	@Override
	protected void setupUpdate(Person entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		update.setInt(3, entity.getId());
		
	}

	public List<Person> withName(String name) {
		// TODO Auto-generated method stub
		return null;
	}
	
	
}
